/**
 * Constants for the motivational-quote card (ARCHITECTURE.md §3, §7; D11/D12). The card is
 * decorative: it shows one short, original, finance-relevant reminder on the Transactions, Budgets
 * and Goals pages. Everything the feature needs — the categories, the fixed system prompt, the
 * curated fallback lines, the cache windows and the dedicated quota key — is gathered here so the
 * service and validation layers stay thin.
 *
 * Nothing here is built from user input: the only per-request variable is the category (an enum) and
 * the small recent-quote history the service feeds back to avoid repeats (R-I3). No user data ever
 * reaches the model (R-I1) — quotes are generic public text, which is why one cached line per
 * category can be shared across every user (D11).
 */

/** The only three sections that carry the card. Also the enum the route validates against. */
export const QUOTE_CATEGORIES = ['transactions', 'budgets', 'goals'] as const;

export type QuoteCategory = (typeof QUOTE_CATEGORIES)[number];

/** The wire shape `GET /quotes/:category` returns; `source` tells the client which line it got. */
export interface QuoteResult {
  quote: string;
  category: QuoteCategory;
  source: 'ai' | 'fallback';
  disclaimer: string;
}

/**
 * What each section's quote should be *about*. Fed to the model as guidance, never shown to the
 * user. Kept general and finance-relevant so a generated line always fits the page it sits on.
 */
export const QUOTE_TOPICS: Record<QuoteCategory, string> = {
  transactions:
    'mindful spending, tracking where money goes, spending habits, financial awareness, and intentional day-to-day money decisions',
  budgets:
    'budgeting, financial discipline, planning ahead, controlling unnecessary expenses, needs versus wants, and staying within a budget',
  goals:
    'financial goals, consistency, patience, steady progress, saving toward a target, long-term planning, and staying motivated',
};

/** The one disclaimer text, carried in the API payload and the card's accessible label only (R-I5). */
export const QUOTE_DISCLAIMER =
  'A general motivational reminder generated by AI — for encouragement only, not financial advice.';

/**
 * How long a generated line is served before a refresh is attempted (~12h), and how long past that
 * a stale line may still be served while a refresh runs (~another 12h → ~24h total). Rotating on
 * this cadence keeps app-wide generation at ~6 calls/day across the three sections (D11, §8).
 */
export const QUOTE_CACHE_FRESH_MS = 12 * 60 * 60 * 1000;
export const QUOTE_CACHE_STALE_MS = 12 * 60 * 60 * 1000;

/** How many recent quotes per category are fed back to the model so it does not repeat itself. */
export const QUOTE_HISTORY_SIZE = 10;

/** Word bounds for a generated line. A little slack around the documented ~8–25 so a good line is
 *  not rejected for a word or two, while a runaway response is still capped (R-I4). */
export const QUOTE_WORD_MIN = 5;
export const QUOTE_WORD_MAX = 30;

/** A hard character cap on the quote, independent of word count, to bound abusive output (R-I4/R-B8). */
export const QUOTE_TEXT_MAX_CHARS = 240;

/**
 * The dedicated quota key passed to the AI Service for every quote generation (D12). It buckets the
 * best-effort per-"user" AI quota (R-I6) under one fixed sentinel, so decorative generation can
 * never deplete a real user's 15/hr·50/day financial-AI budget. The model never sees this string and
 * it never reaches Prisma (R-I1).
 */
export const QUOTE_QUOTA_KEY = 'motivational-quotes';

/**
 * The fixed, server-side system prompt for quote generation (R-I3). It states the rules a line must
 * follow — length, originality, finance-relevance, and the hard "no advice / no guarantees / no
 * attributions / no fake statistics / no guilt" bans — and pins the JSON output shape (R-I4). It is
 * a constant: no user free-text is ever interpolated into it.
 */
export const QUOTE_SYSTEM_PROMPT = [
  "You write one short, original motivational line for Finora, a personal-finance app.",
  `The line must be between ${String(QUOTE_WORD_MIN)} and ${String(QUOTE_WORD_MAX)} words — ideally 8 to 25 — concise, warm, and natural to read.`,
  'It must be relevant to personal finance and to the specific section named in the request. Do not write a generic, non-financial quote.',
  'Write your own original line. Do NOT quote, attribute, or imitate any real person, book, or famous saying, and never add an author or source.',
  'Never promise or guarantee any financial outcome, give investment, tax, or legal advice, cite any statistic or number, or use guilt, shame, or fear.',
  'Keep it encouraging and inclusive. Avoid clichés and avoid repeating any of the recent lines you are shown.',
  'Reply with ONLY a single JSON object of the form {"quote": "...", "category": "..."} — no markdown, no code fences, and no text before or after the JSON.',
].join('\n');

/**
 * Build the user message for one generation: the section, its topic guidance, and the recent lines
 * to avoid. Pure and side-effect-free; the recent list is generic public text, never user data.
 */
export function buildQuoteUserPrompt(category: QuoteCategory, recent: readonly string[]): string {
  const lines = [
    `Section: ${category}.`,
    `Write a line about: ${QUOTE_TOPICS[category]}.`,
    'Return that exact section string in the "category" field.',
  ];

  if (recent.length > 0) {
    lines.push('Do not repeat or closely paraphrase any of these recent lines:');
    for (const line of recent) {
      lines.push(`- ${line}`);
    }
  }

  return lines.join('\n');
}

/**
 * Curated fallback lines — the server's OWN copy (the client keeps a separate one; the repos never
 * share code, R-N7). Served verbatim whenever generation is unavailable, rate-limited, times out, or
 * returns something unusable, so the card — and the page it sits on — never breaks (§9). Each line
 * is original, finance-relevant, within the word bounds, and free of advice, guarantees, and
 * attributions, matching the rules the model is held to.
 */
export const QUOTE_FALLBACKS: Record<QuoteCategory, readonly string[]> = {
  transactions: [
    'Every amount you record is a small act of awareness, and awareness is where better money habits begin.',
    'Money leaves quietly in the small purchases; noticing each one is how you stay in control of it.',
    'You cannot steer what you never look at, so watching where your money goes is already progress.',
    'Each transaction you track turns a vague worry about spending into something you can actually see.',
    'Mindful spending is not spending less on everything, but spending on purpose more of the time.',
    'The habit of writing it down today is what makes tomorrow’s decisions feel calm and clear.',
  ],
  budgets: [
    'A budget is not a cage; it is a plan that lets you spend without quiet guilt afterward.',
    'Deciding where your money should go before it arrives is how you stop wondering where it went.',
    'Discipline with a budget is really just kindness to the version of you who comes next month.',
    'Knowing the difference between what you need and what you want is quiet financial strength.',
    'Small limits kept consistently do more for your budget than big sacrifices made only once.',
    'A budget works best when it reflects your real life, not the life you think you should have.',
  ],
  goals: [
    'Progress toward a goal is rarely loud; it is the quiet result of showing up again and again.',
    'Patience and consistency will carry a savings goal further than any single burst of effort.',
    'Every small amount set aside is a promise kept to the future you are quietly building toward.',
    'Goals feel distant until you break them into steps small enough to take one this week.',
    'Staying steady through slow months is what turns a hopeful goal into a reached one.',
    'You do not need a perfect month to move forward, only a consistent willingness to keep going.',
  ],
};

